sudo: required
services:
  - docker

before_install:
  - docker build -t evgenipirianov/docker-react  -f Dockerfile.dev .

script:
  - docker run evgenipirianov/docker-react npm run test -- --coverage
